### ISSUE TITLE
Infinite loop in Debug builds

### ISSUE THREAD

**Issue by jonfunkhouser** [pointfreeco/xctest-dynamic-overlay#18]
I updated my app to TCA 0.38.2 and xctest-dynamic-overlay 0.3.0. There's a case in my app where an optional Reducer can run against nil state (which I need to fix). In a Debug build running on the Simulator, this triggers a `runtimeWarning`, which calls `XCTFail`, which then calls `runtimeWarning`, and this loop continues until Xcode crashes.

Here's a minimal app that reproduces the issue. Pressing the "Increment" button in the Simulator will trigger the loop:
```
import ComposableArchitecture
import SwiftUI

struct RootState: Equatable {
  var optional: OptionalState? = nil
}

struct OptionalState: Equatable {
  var counter: Int = 0
}

enum OptionalAction {
  case increment
}

let optionalReducer = Reducer<OptionalState, OptionalAction, Void> { state, action, _ in
  switch action {
  case .increment:
    state.counter = state.counter + 1
    return .none
  }
}

enum RootAction {
  case optional(OptionalAction)
}

let rootReducer = Reducer<RootState, RootAction, Void>.combine(
  optionalReducer
    .optional()
    .pullback(
      state: \.optional,
      action: /RootAction.optional,
      environment: { }
  ),
  .init { state, action, _ in
    return .none
  }
)

struct RootView: View {
  let store = Store(initialState: RootState(), reducer: rootReducer, environment: ())
  
  var body: some View {
    NavigationView {
      VStack {
        Text("Root View")
        WithViewStore(store) { viewStore in
          Button("Increment") { viewStore.send(.optional(.increment)) }
        }
      }
    }
  }
}

@main
struct TestApp: App {
  var body: some Scene {
    WindowGroup {
      RootView()
    }
  }
}
```

**Comment by stephencelis** [comment]
@jonfunkhouser Oops, sorry about that! I've pushed a fix here #19. If it's not too much trouble can you verify this fixes things for you?

**Comment by jonfunkhouser** [comment]
Yes that fixed it, thank you!

**Comment by stephencelis** [comment]
Verified locally, and pushed https://github.com/pointfreeco/xctest-dynamic-overlay/releases/tag/0.3.1

Let us know if you have any issues, and thanks for the quick report!
