### ISSUE TITLE
XCTUnimplemented placeholder .none vs. Effect.none

### ISSUE THREAD

**Issue by rcarver** [pointfreeco/xctest-dynamic-overlay#26]
With TCA, when you used `XCTUnimplemented` to stub out a function returning an `Effect` I instinctively use `placeholder: .none` and then get surprised when it fatal errors. You have to explicitly use `Effect.none` to get a nice test error instead.

```swift
struct Client {
    var perform: () -> Effect<Void, Never>
    static let unimplemented1 = Self(
        perform: XCTUnimplemented("perform", placeholder: .none)
    )
    static let unimplemented2 = Self(
        perform: XCTUnimplemented("perform", placeholder: Effect.none)
    )
}
```

**Comment by stephencelis** [comment]
@rcarver I think this is definitely a gotcha, and @mbrandonw and I have chatted briefly about adding more specific overloads to those endpoints (to take a non-optional or no argument at all).

We haven't gotten around to this yet, but hopefully soon! If you (or someone else) decide to take a stab at this refactor, though, we'd be happy to take a PR!

**Comment by rcarver** [comment]
Thank you @stephencelis! I just got hit by a fatal error, pulled #29 and it fails nicely with no changes.
