### ISSUE TITLE
Incorrect Information in README

### ISSUE THREAD

**Issue by Peter-Schorn** [pointfreeco/xctest-dynamic-overlay#3]
In the README, it says
> However, as soon as you add import XCTest to a source file in your application or a library it loads, the target becomes unbuildable:

But, actually, there is a way to build projects that import XCTest in a non-test target:

For the project build settings, search for "Runpath Search Paths" and add the following paths:

* /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/
* /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/

For the project build settings, set "Enable Testing Search Paths" to "Yes"

This may only work in macOS projects

**Comment by stephencelis** [comment]
@Peter-Schorn While it is true that you can add the test search paths to the binary, this just kicks the can down the road, unfortunately, and you will run into problems when this code is compiled to run in an executable on a device. While there may be certain permutations that don't run into problems (Linux, for example, seems to import XCTest just fine), in your typical iOS workflow it does not seem possible to `import XCTest` with abandon and expect things to work 😞
