### ISSUE TITLE
Long build times when using `XCTUnimplemented` on type with many closures 

### ISSUE THREAD

**Issue by wattson12** [pointfreeco/xctest-dynamic-overlay#30]
## Summary 

I am introducing `XCTUnimplemented` for a TCA based feature but was running into long build times once I started mocking an environment with 6 closures. 

Attached is a test app with a simple environment, 1 function that uses is and a test which calls that function. With the `.unimplemented` code the build times go from <1s to > 90s 

Changing `f: XCTUnimplemented("\(Self.self).f")` to `f: { _ in fatalError() }` and leaving the other unimplemented calls in place restores the original build time 

This is using `0.4.0`

## Project

[XCTUnimplementedIssue.zip](https://github.com/pointfreeco/xctest-dynamic-overlay/files/9292941/XCTUnimplementedIssue.zip)

## Environment + `.unimplemented` 

```
struct Environment {
    let a: () -> Bool
    let b: () -> Bool
    let c: () -> Void
    let d: () -> Void
    let e: (Bool) -> Void
    let f: (Bool) -> Void
}
```

```
extension Environment {
    static let unimplemented: Environment = .init(
        a: XCTUnimplemented("\(Self.self).a", placeholder: Bool.random()),
        b: XCTUnimplemented("\(Self.self).b", placeholder: Bool.random()),
        c: XCTUnimplemented("\(Self.self).c"),
        d: XCTUnimplemented("\(Self.self).d"),
        e: XCTUnimplemented("\(Self.self).e"),
        f: XCTUnimplemented("\(Self.self).f")
    )
}
```

**Comment by stephencelis** [comment]
@wattson12 Hm, the project builds for me from clean in about 3 seconds. Can you provide more info? Xcode/Swift version, etc.?

**Comment by wattson12** [comment]
Adding my comment from slack, if I swap 
```
: Environment = .init(
```
for 
```
: Environment = Self(
```
The build times are back under a second

**Comment by stephencelis** [comment]
Ah, sounds like the bug's on Apple's end, then! Wanna file it with them and link here?

**Comment by stephencelis** [comment]
@wattson12 Just curious if you ever filed a bug with Apple? Just had a related report in a totally different repo.

**Comment by wattson12** [comment]
> @wattson12 Just curious if you ever filed a bug with Apple? Just had a related report in a totally different repo.

It was on my list but thanks for the reminder 😄 raised here https://github.com/apple/swift/issues/61079. Feel free to add any other context from the other report

**Comment by JCSooHwanCho** [comment]
Although Long time has passed, I met same problem with Swift 5.9(Xcode 15).

For the anyone who finds workaround, I wanna leave my experience.

For reference, my build device specification
> MacBook Pro 16, M1 Max, 64GB RAM, 1TB.

BaseCode
```swift
import Foundation
import XCTestDynamicOverlay

public struct EndPoints {
    public var endPoint1: @Sendable () -> Void
    public var endPoint2: @Sendable () -> String
    public var endPoint3: @Sendable () -> Int
    public var endPoint4: @Sendable () -> Double
    public var endPoint5: @Sendable () -> Data?

    public init(
        endPoint1: @escaping @Sendable () -> Void,
        endPoint2: @escaping @Sendable () -> String,
        endPoint3: @escaping @Sendable () -> Int,
        endPoint4: @escaping @Sendable () -> Double,
        endPoint5: @escaping @Sendable () -> Data?
    ) {
        self.endPoint1 = endPoint1
        self.endPoint2 = endPoint2
        self.endPoint3 = endPoint3
        self.endPoint4 = endPoint4
        self.endPoint5 = endPoint5
    }
}
```
Build Time: 0.2s

When Problematic code added
```swift
extension EndPoints {
    static var value: EndPoints {
        .init(
            endPoint1: unimplemented(),
            endPoint2: unimplemented(),
            endPoint3: unimplemented(),
            endPoint4: unimplemented(),
            endPoint5: unimplemented()
        )
    }
}
```
Build Time: 160.8s

When both description and placeholder parameter filled
```swift
extension EndPoints {
    static var value: EndPoints {
        .init(
            endPoint1: unimplemented("endPoint1 unimplemented"),
            endPoint2: unimplemented("endPoint2 unimplemented", placeholder: ""),
            endPoint3: unimplemented("endPoint3 unimplemented", placeholder: 0),
            endPoint4: unimplemented("endPoint4 unimplemented", placeholder: 0.0),
            endPoint5: unimplemented("endPoint5 unimplemented", placeholder: nil)
        )
    }
}
```
Build Time: 24.4s

Even though build time is still too long, It reduces build time dramatically. In our company's project case, it shows more sharp reduction of build time.
