### ISSUE TITLE
Crash when checking XCTCurrentTestCase

### ISSUE THREAD

**Issue by htrcarlos** [pointfreeco/xctest-dynamic-overlay#34]
Hi everyone,

My app uses TCA framework and I noticed a crash on the latest version (0.5.0) when XCTCurrentTestCase variable is computed. The crash happens as `XCTestObservationCenter` variable is NSNull and it tries to perform `sharedTestObservationCenter` selector.

```(swift)
...
line 10: let shared = XCTestObservationCenter.perform(Selector(("sharedTestObservationCenter")))?
          .takeUnretainedValue(),
...
```
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull sharedTestObservationCenter]: unrecognized selector sent to instance 0x10fa51590'
```

Thanks,
Heitor

**Comment by stephencelis** [comment]
Hi @htrcarlos! Has anything else changed in your system? The body of `_XCTCurrentTestCase` hasn't changed, though it is invoked in a new place when checking to see if tests are running.

Can you share a repro so we can cook up a fix?

**Comment by htrcarlos** [comment]
Hi @stephencelis, thanks for having a look into this. I've tried to create a new project to reproduce the issue, but no luck so far. Also, I can't share the project that is crashing because it is a company app which is really old and uses a lot objective-c code.

I suppose the problem is related to some project configuration maybe, but I'm not sure. Now all I can say is that my app crashes as the string comparison for `XCTestObservationCenter` fails because its value is just empty and not `<null>` as expected.
```swift
...
String(describing: XCTestObservationCenter) != "<null>",
...
```
I'll continue to work on a different solution and see if I can get the crash on that.

**Comment by stephencelis** [comment]
@htrcarlos If it's reproducible and you can set a breakpoint and troubleshoot a fix we'd be happy to take it. We don't think it'd be difficult to work around but without a repro it's difficult for us to test things out.

**Comment by htrcarlos** [comment]
Just realised my app had an extension and it was overwriting NSNull description to be empty, after removing it all worked fine 😅
I'm happy to close this issue as it was more a project issue.
Thanks again @stephencelis

**Comment by stephencelis** [comment]
@htrcarlos By overwriting you mean conforming `NSNull` to return `""`? Can you share the repro now? Still feels like something that shouldn't crash if we can avoid it.

**Comment by htrcarlos** [comment]
Yeah, so in my app case the NSNull description property was overwritten in some objective-c file, but I managed to reproduce the same crash after adding an extension on a swift file.

I've attached a demo project so you can have a look when you have a chance.
Thanks! 
[DemoApp.zip](https://github.com/pointfreeco/xctest-dynamic-overlay/files/9912520/DemoApp.zip)
