### ISSUE TITLE
Cannot open "Documentation.docc" as a "Swift Package Folder" because it is already open as a "Folder"

### ISSUE THREAD

**Issue by huwr** [pointfreeco/xctest-dynamic-overlay#35]
Hi,

I'm having an issue building this package. It's only started since we moved to Xcode 14 and 14.1. When archiving with `xcodebuild` it reports:

```
2022-11-06 22:12:10.919 xcodebuild[5632:81577] [MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x600003fa1400: name:Documentation.docc path:group:Documentation.docc> Failed to load container at path: /Users/runner/Library/Developer/Xcode/DerivedData/XXXXXX-flaewjllgygaoobtikmjykvcbuow/SourcePackages/checkouts/xctest-dynamic-overlay/Sources/XCTestDynamicOverlay/Documentation.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Documentation.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Documentation.docc" as a "Swift Package Folder" because it is already open as a "Folder".}
```

Or more easily:

```
Cannot open "Documentation.docc" as a "Swift Package Folder" because it is already open as a "Folder"
```

Really unsure as to what we can do here. We're brining XCTDynamicOverlay as a transitive dependency via [SwiftUI-Navigation](https://github.com/pointfreeco/swiftui-navigation/blob/main/Package.swift#L21). 

If it helps, here's a (sanitised) version of our xcodebuild command:

```sh
xcodebuild -workspace XXXXXX.xcworkspace -scheme XXXXXX -sdk iphoneos -disableAutomaticPackageResolution -archivePath 'Build/XXXXXX.xcarchive' archive -xcconfig XXXXXX/XXXXXX/Resources/Config/Distribution-AppStore.xcconfig XXXXXX_BUILD_NUMBER=477
```

**Comment by huwr** [comment]
Little more background: A very similar issue occurred over in Nuke: https://github.com/kean/Nuke/issues/609 Their solution was actually to remove the docc folders 😢

**Comment by huwr** [comment]
Okay, I'm closing the issue because it's not actually a problem. It was a bit of a red-herring. My main issue was solved in a very similar way to other people's [here](https://forums.swift.org/t/xcode-14-beta-code-signing-issues-when-spm-targets-include-resources/59685/13).

**Comment by mbrandonw** [comment]
Hi @huwr, thanks for looking into it more and letting us know what the underlying issue was. Glad we don't have to move docs out of `Sources/`, but also still bizarre how a provisioning profile setting would surface an error about docs. 😐

**Comment by huwr** [comment]
Yeah. It's actually a totally separate issue. I still have the original error, in fact, but it is not causing any archive failures! I downgraded temporarily back to SwiftUI-Navigation 0.2.0 (which didn't have XCTestDynamicOverlay) and the warning went away, but the archive failure persisted. It turns out, there was errors elsewhere that my CI had made less than obvious. Just thought I'd leave the link to the solution in the thread in case someone finds this same issue and is having a similar trouble.

**Comment by marinofelipe** [comment]
What solved for me in the project I work on was to add the `.docc` relative path to the target's `exclude`

```swift
.target(
    name: "MyTarget",
    // ...
    exclude: ["PathToDocc/MyDocs.docc"]
  ),
```

> The paths to source and resource files that you don’t want to include in the target.
https://developer.apple.com/documentation/packagedescription/target/exclude

It looks like xcodebuild / Swift compiler considers that as valid (re)source path which causes those log entries.
After excluding the logs were gone, and docc can still be compiled via the `Build Documentation` option / `xcodebuild docbuild`
