### ISSUE TITLE
Delay load for XCTFail looks broken, and needs a Windows equivalent

### ISSUE THREAD

**Issue by tonyschr** [pointfreeco/xctest-dynamic-overlay#44]
I was creating a patch to use LoadLibrary and GetProcAddress for Windows, similar to `dlsym(dlopen(nil, RTLD_LAZY), "_XCTFailureHandler"),`, when I realized there is no `_XCTFailureHandler` export.

It looks like it doesn't exist anymore, even internally, but as a Windows dev I could be missing something.

**Comment by stephencelis** [comment]
Hi @tonyschr!

The `_XCTFailureHandler` symbol should be limited to `#if canImport(ObjectiveC)` and not run on either Windows or Linux. On non-Apple platforms it should just fall through to `import XCTest`, which seems to be a valid thing to do.

Are you experiencing a bug with the library that can be reproduced? Maybe you'd like to explore getting Windows running on our continuous integration here? https://github.com/pointfreeco/xctest-dynamic-overlay/blob/ab8c9f45843694dd16be4297e6d44c0634fd9913/.github/workflows/ci.yml

**Comment by tonyschr** [comment]
First, we've investigated this more thoroughly and as part of a larger effort, we're doing what's needed on our side and will upstream what makes sense for Windows. I'm part of The Browser Company and didn't realize how close of a connection your team had already. :)

**Comment by tonyschr** [comment]
Second, as ex-MSFT, my read of the code was that this was delay-load logic instead of requiring a static dependency on XCTest.dll. The static XCTest.dll dependency (which is outside the DLL search order) seemed undesirable. Hence this issue/question.

Having our debug builds copy the XCTest.dll binary is the solution we're using. LoadLibrary/GetProcAddress on the actual XCTest binary and fail softly seems better. This is what we're contemplating.

You can close this issue. Thanks.

**Comment by stephencelis** [comment]
Thanks for the update! We will close, but are very open to improvements here that you make.
